image: node:10

pipelines:
  branches:
    master:
    - step:
        services:
          - docker
        script:
          - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD $DOCKER_REGISTRY_URL
          - docker build -t $DOCKER_REGISTRY_URL/$BITBUCKET_REPO_SLUG:latest .
          - docker push $DOCKER_REGISTRY_URL/$BITBUCKET_REPO_SLUG:latest
    # - step:
    #     name: Deploy to Development
    #     deployment: test
    #     script:
    #       - ssh root@server.jok.io 'git archive --remote=ssh://git@bitbucket.org/jokio/jokio-docker.git master deploy.sh | sh'
