version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: sudo yarn global add semantic-release @semantic-release/changelog @semantic-release/git
      - run: yarn install
      - run: yarn test
      - run: semantic-release

workflows:
  version: 2
  main-workflow:
    jobs:
      - build:
          context: deployment
